"use client";

import Navbar from "@/components/Navbar";
import { usePrivy } from "@privy-io/react-auth";
import { useEffect, useMemo, useState } from "react";
import {
  clearCreations,
  getUserKeyFromPrivyUser,
  listCreations,
  removeCreation,
  subscribeCreations,
  type StoredCreation,
} from "@/lib/creations";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export default function MyGalleryPage() {
  const { ready, authenticated, user, login } = usePrivy();
  const userKey = useMemo(() => getUserKeyFromPrivyUser(user), [user]);
  const [items, setItems] = useState<StoredCreation[]>([]);

  useEffect(() => {
    if (!userKey) {
      setItems([]);
      return;
    }
    setItems(listCreations(userKey));
    return subscribeCreations(userKey, setItems);
  }, [userKey]);

  if (!ready) {
    return (
      <div className="min-h-screen bg-background pt-16">
        <Navbar />
        <main className="w-full px-6 lg:px-8 py-6">
          <p className="text-muted-foreground" data-testid="text-loading">
            Loading...
          </p>
        </main>
      </div>
    );
  }

  if (!authenticated || !userKey) {
    return (
      <div className="min-h-screen bg-background pt-16">
        <Navbar />
        <main className="w-full px-6 lg:px-8 py-10 max-w-5xl mx-auto">
          <Card className="border border-border/60 bg-card/60 backdrop-blur">
            <CardHeader>
              <CardTitle>My Gallery</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <p className="text-sm text-muted-foreground">
                Log in to view your private creations.
              </p>
              <Button onClick={login} data-testid="button-login-my-gallery">
                Log in
              </Button>
            </CardContent>
          </Card>
        </main>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background pt-16">
      <Navbar />
      <main className="w-full px-6 lg:px-8 py-6 max-w-6xl mx-auto">
        <div className="flex items-start justify-between gap-3 mb-4">
          <div>
            <h1 className="text-xl font-semibold text-foreground">
              My Gallery
            </h1>
            <p className="text-sm text-muted-foreground">
              Private creations generated by you.
            </p>
          </div>
          <Button
            variant="outline"
            onClick={() => clearCreations(userKey)}
            disabled={items.length === 0}
            data-testid="button-clear-my-gallery"
          >
            Clear
          </Button>
        </div>

        {items.length === 0 ? (
          <Card className="border border-border/60 bg-card/60 backdrop-blur">
            <CardContent className="py-10 text-center text-sm text-muted-foreground">
              No creations yet. Generate an image and it will appear here.
            </CardContent>
          </Card>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {items.map((c) => (
              <Card
                key={c.id}
                className="border border-border/60 bg-card/60 backdrop-blur overflow-hidden"
                data-testid={`my-creation-${c.id}`}
              >
                <div className="aspect-[4/3] bg-muted">
                  <img
                    src={c.imageUrl}
                    alt="Generated"
                    className="w-full h-full object-cover"
                  />
                </div>
                <CardContent className="p-3 space-y-2">
                  <div className="flex items-center justify-between gap-2">
                    <div className="text-xs text-muted-foreground">
                      {new Date(c.createdAt).toLocaleString()}
                    </div>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-7 px-2"
                      onClick={() => removeCreation(userKey, c.id)}
                      data-testid={`button-delete-creation-${c.id}`}
                    >
                      Remove
                    </Button>
                  </div>
                  <div className="text-xs font-mono text-foreground/80 whitespace-pre-wrap break-words max-h-24 overflow-y-auto scrollbar-thin">
                    {c.prompt}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
